import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  // test json const
  const testJson = { message: "your test is here" };
  return (
    <div className={styles.container}>
      <Head>
        <title>Heart Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Heart Checker</a>
        </h1>

        <button
          onClick={async () => {
            // use axios to send post to /api/checker
            const response = await axios.post("/api/test", testJson);
            console.log("response", response);
          }}
          // console.log("axios", axios);
        >
          Test API
        </button>

        {/* <p className={styles.description}>
          Latest heart rate: <b>75</b>
        </p> */}
      </main>
    </div>
  );
}
